FROM node:17-alpine3.14 AS prod
WORKDIR /app/parent-app
COPY .npmrc ./
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build
RUN rm -f .npmrc


FROM nginx
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=prod ./app/parent-app/build /usr/share/nginx/html